FROM jenkins/jenkins:2.235.5-lts-jdk11

# Installation de Maven
USER root
RUN apt-get update && apt-get install -y maven


USER jenkins

# Copy plugin list and install on startup
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Copy seedJob config
COPY seedJob.xml /usr/share/jenkins/ref/jobs/seed-job/config.xml

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false